# Generated by Django 6.0.1 on 2026-01-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_gstdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Standing', 'Standing'), ('Approved', 'Approved'), ('Accounted', 'Accounted'), ('Rejected', 'Rejected'), ('Hold', 'Hold')], default='Standing', max_length=20),
        ),
    ]
