# Generated by Django 6.0.1 on 2026-02-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_invoice_validation_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='raw_ocr_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
