# Generated by Django 6.0.1 on 2026-03-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_invoice_raw_ocr_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='pan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
