# Generated by Django 6.0.1 on 2026-03-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_companydetails_pan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='pan',
            field=models.CharField(default='ABCDE1234F', max_length=10),
            preserve_default=False,
        ),
    ]
