# Generated by Django 6.0.1 on 2026-03-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_companydetails_pan'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsn_code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('block_credit', models.CharField(blank=True, max_length=2, null=True)),
                ('rcm', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sac_code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('block_credit', models.CharField(blank=True, max_length=2, null=True)),
                ('rcm', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
