# Generated by Django 6.0.1 on 2026-03-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_hsn_sac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsn',
            name='block_credit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sac',
            name='block_credit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
