# Generated by Django 6.0.1 on 2026-03-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_hsn_block_credit_alter_sac_block_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('APP_ADMIN', 'App Admin'), ('COMPANY_ADMIN', 'Company Admin'), ('PROCESSOR', 'Processor')], max_length=20),
        ),
    ]
