# Generated by Django 6.0.1 on 2026-03-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_invoiceremark'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='max_invoices',
            field=models.IntegerField(default=100),
        ),
    ]
