# Generated by Django 6.0.1 on 2026-04-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_companydetails_max_invoices'),
    ]

    operations = [
        migrations.CreateModel(
            name='EInvoiceRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_gstin', models.CharField(max_length=20)),
                ('document_number', models.CharField(max_length=50)),
                ('document_date', models.DateField()),
                ('supply_type', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('eway_bill_no', models.CharField(blank=True, max_length=50, null=True)),
                ('irn', models.CharField(max_length=100, unique=True)),
                ('irn_status', models.CharField(max_length=20)),
                ('ack_no', models.CharField(max_length=50)),
                ('irn_date', models.DateTimeField()),
            ],
        ),
    ]
