from .data_gathering import api_response_test


def build_validation_summary(api_response=api_response_test):

    summary = []

    checks = api_response.get("result", {}).get("CHECKS", {})


    #------------------------------------------------------------------
    # 1. Complete Invoice Check
    #------------------------------------------------------------------
    complete_invoice = (
        checks.get("Account_check", {})
              .get("Complete_Invoice", {})
    )

    status = complete_invoice.get("status")

    
    summary.append({
        "check_type": "Complete Invoice",
        "status": "✓ Passed" if status == "YES" else "✗ Failed",
        "details": "All mandatory invoice fields are present"
                   if status == "YES"
                   else "Invoice data is incomplete",
        "result": "Valid" if status == "YES" else "Invalid"
    })


    #------------------------------------------------------------------
    # 2. Vendor GST Validation
    #------------------------------------------------------------------

    vendor_gst = (
        checks.get("tax_check", {})
              .get("Vendor_Gst_Valid", {})
    )

    gst_status = vendor_gst.get("status")

    summary.append({
        "check_type": "Vendor GST Validation",
        "status": "✓ Passed" if gst_status == "YES" else "✗ Failed",
        "details": vendor_gst.get("Gst_Portal", "GST check executed"),
        "result": "Valid" if gst_status == "YES" else "Invalid"
    })
    

    #------------------------------------------------------------------
    # 3. Vendor Name Match
    #------------------------------------------------------------------

    vendor_name = (
        checks.get("Account_check", {})
              .get("Customer_Name", {})
 
    )

    name_status = vendor_name.get("status")

    summary.append({
        "check_type": "Vendor Name Match",
        "status": "✓ Passed" if name_status == "Matching" else "✗ Failed",
        "details": "Invoice vendor matches GST portal data"
                   if name_status == "Matching"
                   else "Vendor name mismatch",
        "result": "Valid" if name_status == "Matching" else "Invalid"
    })


    #------------------------------------------------------------------
    # 4. Invoice Amount Validation
    #------------------------------------------------------------------

    eway = checks.get("eway_bill_data", {})
    eway_status = eway.get("status")

    summary.append({
        "check_type": "E-Way Bill Validation",
        "status": "✓ Passed" if eway_status == "okay" else "✗ Failed",
        "details": eway.get("reason", "E-way bill check performed"),
        "result": "Valid" if eway_status == "okay" else "Invalid"
    })


    return summary


# Invoice validation summary cab be generated by calling the function
# validation_summary = build_validation_summary()
